/*
===============================================================================
                                                                        CCOUT.C
                                                             Output coordinates
===============================================================================
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "cdim.h"

extern float X[][DIMA+1],Y[][DIMA+1],Z[][DIMA+1];
extern int   atnum[][DIMA+1],rsnum[][DIMA+1];
extern int   mnum[],nat[];
extern int   nmol;
extern char  atnam[][DIMA+1][4],rsnam[][DIMA+1][4];
extern FILE  *fopen(),*fout;

void ccout(int nst)
{
double value;
int    i,ii,im,im2,k,j,nt,dc,sn;
char   pdbn[100],*work;

      ii=-1; pdbn[++ii]='t'; value=(double)nst; work=ecvt(value,10,&dc,&sn);
      for (i=0;i<dc;i++) { pdbn[++ii]=work[i]; }
      pdbn[++ii]='.';pdbn[++ii]='p';pdbn[++ii]='d';pdbn[++ii]='b';pdbn[++ii]='\0';
      fout=fopen(pdbn,"w");
      
      fprintf(fout,  "REMARK  Molecular environment");
      fprintf(fout,"\nREMARK  Generated by GRAMMCell"); 
      fprintf(fout,"\nREMARK");
      im2=0;
 
      for (i=1; i<=nmol; i++)
        {
         im=mnum[i]; nt=nat[im];
//printf("\nmnum[%d]=%d nt=%d",i,mnum[i],nt);
         if (im!=im2) { im2=im; j=1; }
         fprintf(fout,"\nMODEL %8d",j); j++;
         for (k=1; k<=nt; k++)
           {
            fprintf(fout,"\nATOM  %5d %c%c%c%c%c%c%c%c %-2d%3d",
               atnum[im][k],
               atnam[im][k][0],atnam[im][k][1],atnam[im][k][2],atnam[im][k][3],
               rsnam[im][k][0],rsnam[im][k][1],rsnam[im][k][2],rsnam[im][k][3],
               im,rsnum[im][k]);
            fprintf(fout,"    %8.3f%8.3f%8.3f",X[i][k],Y[i][k],Z[i][k]);
           }
         fprintf(fout,"\nATOM      1  M   CMS     0    ");                // CM
         fprintf(fout,"%8.3f%8.3f%8.3f",X[i][0],Y[i][0],Z[i][0]);
         fprintf(fout,"\nTER");
        }
      fclose(fout);
}
